// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLKHO1.Data;

#nullable disable

namespace QLKHO1.Migrations
{
    [DbContext(typeof(PhieuNhapDbContext))]
    partial class PhieuNhapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLKHO1.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhieuNhapSoPhieuNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("SoPhieuNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatTuMaVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PhieuNhapSoPhieuNhap");

                    b.HasIndex("VatTuMaVatTu");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLKHO1.Models.PhieuNhap", b =>
                {
                    b.Property<string>("SoPhieuNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoPhieuNhap");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("QLKHO1.Models.VatTu", b =>
                {
                    b.Property<string>("MaVatTu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DinhMucTon")
                        .HasColumnType("int");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVatTu");

                    b.ToTable("VatTus");
                });

            modelBuilder.Entity("QLKHO1.Models.ViTri", b =>
                {
                    b.Property<string>("MaViTri")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SucChua")
                        .HasColumnType("float");

                    b.Property<double>("SucChuaConLai")
                        .HasColumnType("float");

                    b.HasKey("MaViTri");

                    b.ToTable("ViTris");
                });

            modelBuilder.Entity("QLKHO1.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLKHO1.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("PhieuNhapSoPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKHO1.Models.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("VatTuMaVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QLKHO1.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
